from src.data import Data   


class Features(Data):
        
    def __init__(self):
        super().__init__()

    def feature(self):
        df = self.data_cleaning()
        df['ret_1'] = df['Close'].pct_change(1) # % change from yesterday
        df['ret_3'] = df['Close'].pct_change(3) # % change from  3 day before
        df['ma_5']  = df['Close'].rolling(5).mean() # 5 day moving average(fast)
        df['ma_10'] = df['Close'].rolling(10).mean() # 10 day moving average (medium)
        df['ma_20'] = df['Close'].rolling(20).mean() # 20 day moving average (slow)
        df['std_10'] = df['Close'].rolling(10).std() # flacutuation in the market (standard devation)
        df['mom_5'] = df['Close'] - df['Close'].shift(5) # Momentum means speed of movement

        # Simple RSI implementation (14-period)
        delta = df['Close'].diff()
        up = delta.clip(lower=0)
        down = -1 * delta.clip(upper=0)
        roll_up = up.rolling(14).mean()
        roll_down = down.rolling(14).mean()
        rs = roll_up / (roll_down + 1e-9)
        df['rsi'] = 100 - (100 / (1 + rs))
        # Drop NA rows generated by indicators
        df = df.dropna().copy()

        # LABEL CREATION
        threshold = 0.001
        df['target_ret'] = df['Close'].shift(-1)/ df['Close']-1
        df['target'] = (df['target_ret'] > threshold).astype(int)
        df = df[:-1]

        # print(df.head())

        return df

# f = Features()
# f.feature()
    
